#!/bin/bash
#!/usr/bin/python3

# Check if the PYFILE environment variable is set
if [ -z "$PYFILE" ]; then
    echo "Error: PYFILE environment variable is not set."
    exit 1
fi

# Run the Python script
/usr/bin/python3 "$PYFILE"

